[theme]
base = "light"
primaryColor = "#5C4632"
backgroundColor = "#F7F3EC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2B2118"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
